version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
    networks:
      - recursero-network
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend/recursero-digital
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    depends_on:
      - backend
    networks:
      - recursero-network
    restart: unless-stopped

networks:
  recursero-network:
    driver: bridge

volumes:
  backend_node_modules:
  frontend_node_modules:

