[phases.setup]
nixPkgs = ["nodejs-18_x", "npm-9_x"]

[phases.install]
cmds = [
  "npm install -g concurrently",
  "cd backend && npm install",
  "cd frontend/recursero-digital && npm install"
]

[phases.build]
cmds = [
  "cd backend && npm run build",
  "cd frontend/recursero-digital && npm run build"
]

[start]
cmd = "./start.sh"

[variables]
NODE_ENV = "production"
PORT = "3000"

